### ISSUE TITLE
Implement new mods

### ISSUE THREAD

**Issue by CloneWith** [CloneWith/opsu#3]
Mainly about these new mods:

- Perfect: more friendly than Sudden Death
- Nightcore: it's **really wierd** to make the pitch higher while increasing the speed 💦 
- Cinema: may be useful since existing support for videos

## Todo

- [ ] Mod icons (need design)
- [ ] Rules and implementation in gameplay
- [ ] Necessary UI changes
